server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置Nacos地址
        server-addr: 39.96.75.234:1111 #换成nginx的1111端口，通过nginx代理转发给nacos集群服务器上

management:
  endpoints:
    web:
      exposure:
        include: '*'