server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:NanoSca1pel/commoncloud-config.git #Github上的git仓库名字
          uri: https://github.com/NanoSca1pel/commoncloud-config.git
          ##搜索目录.这个目录指的是github上的目录
          search-paths:
            - commoncloud-config
#          username: lhtao846321@163.com  #没有开启ssh免密登陆的需要配置git帐号密码
#          password: lht846321
      ##读取分支
      label: master
  #rabbit相关配置 15672是web管理界面的端口，5672是MQ访问的端口
  rabbitmq:
    host: 39.96.75.234
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#rabbitmq相关设置 ，暴露 bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'