spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  #路由ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
          filter: #局部过滤器
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id值为1024

        - id: payment_routh2
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
            #- Before=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
            #- Between=2020-03-12T15:44:15.064+08:00[Asia/Shanghai],2020-03-21T15:44:15.064+08:00[Asia/Shanghai]
            #- Cookie=username,admin   #带Cookie，并且username的值为admin
            #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.lht.com,**.lhtao.org  #请求域名格式必须与规范的一致
            #- Method=GET  #只有get请求能通过
            #- Query=username,\d+  #要有参数名为username并且值还要是整数才能路由