server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false标识不向注册中心注册自己
    register-with-eureka: false
    #false标识自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址,如果有多个地址，则用逗号隔开. 集群模式填入其它服务器地址，单机模式只要填入本机地址
      #集群版
      defaultZone: http://eureka7002.com:7002/eureka/
      #单机版
      #defaultZone: http://eureka7001.com:7001/eureka/
#  server:
#    #关闭自我保护机制，保证不可用服务被及时删除。默认是true开启
#    enable-self-preservation: false
#    #清理无效节点的时间间隔,默认60000毫秒
#    eviction-interval-timer-in-ms: 2000
